#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model package_Group9._1D_Task2_2
 Dymola Version 2022 (64-bit), 2021-04-14 translated this at Fri Apr  8 15:14:57 2022

   */

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    7
#define NX2_   1
#define NU_    0
#define NY_    0
#define NW_    22
#define NP_    16
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1432479587
#define NHash2_ -287484183
#define NHash3_ 0
#define NI_    0
#define NRelF_ 1
#define NRel_  1
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    1
#define SizePre_ 0
#define SizeEq_ 7
#define SizeDelay_ 0
#define QNLmax_ 1
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 46
#define NGlobalHelpI_ 23
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="package_Group9._1D_Task2_2";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/miche/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[15]={5 , 3 , 1 , 4 , 6 , 1 , 2 , 1 , 3 , 1 , 5 , 1
   , 7 , 0 , 0};
static int QJacobianGrp0[8]={1, 1, 4, 4, 4, 4, 0, 0};
static int QJacobianGrp1[6]={1, 2 , 2 , 1 , 3 , 0};
static int QJacobianGrp2[8]={0, 3, 3, 3, 0, 0, 3, 0};
static int QJacobianGrp3[6]={1, 5 , 2 , 3 , 4 , 0};
static int QJacobianGrp4[5]={1, 7 , 1 , 3 , 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[6]={
{0, QJacobianGrp0},{1, QJacobianGrp1},{0, QJacobianGrp2},{1, QJacobianGrp3},{1, 
  QJacobianGrp4},{0,0}};
DYMOLA_STATIC double QJacobianCD_[8]={0  , 44 , 50 , 54 , 77 , 64 , 99 , 70};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct)
DYNX(W_,0) = 9.80665;
DYNX(W_,4) = 200;
DYNX(W_,5) = 20000.0;
DYNX(W_,19) = true;
DYNX(W_,20) = false;
DYNX(W_,21) = false;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(W_,12) = 0;
DYNX(X_,6) = 0;
 /* Linear system of equations to solve. */
DYNX(F_,3) = 0.0;
SolveScalarLinearParametric( -DYNX(DP_,12)," -lf", 0.0,"0.0", DYNX(F_,3),
  "der(w_b)");
 /* End of Equation Block */ 

DYNX(W_,10) = DYNX(X_,3)*DYNX(DP_,13);
DYNX(W_,13) = DYNX(DP_,5)*DYNX(W_,10);
DYNX(W_,15) = divGuarded(DYNX(X_,2),"T_WhlRot",DYNX(DP_,7),"Radius");
 /* Linear system of equations to solve. */
DYNX(F_,6) = 0.0;
SolveScalarLinearParametric(DYNX(DP_,11),"m", DYNX(W_,15),"F_xWhl", DYNX(F_,6),
  "der(v_x)");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,0) = DYNX(DP_,12)+DYNX(DP_,13);
DYNX(X_,4) = 0.0;
SolveScalarLinearParametric(DYNX(DYNhelp,0),"lf+lr",  -(DYNX(DP_,6)*DYNX(F_,3)+
  DYNX(W_,13)*DYNX(DYNhelp,0)+DYNX(DP_,11)*DYNX(F_,6)*DYNX(DP_,14)+9.80665*
  DYNX(DP_,11)*DYNX(DP_,12))," -(J_y*der(w_b)+F_dr*(lf+lr)+m*der(v_x)*h+9.80665*(m*lf))",
   DYNX(X_,4),"F_sr");
 /* End of Equation Block */ 

InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,10) = DYNX(X_,3)*DYNX(DP_,13);
DYNX(F_,4) = DYNX(DP_,4)*DYNX(W_,10);
if (NewParameters_) {
DYNX(DYNhelp,1) = divinvGuarded(DYNX(DP_,7),"Radius");
}
DYNX(W_,15) = DYNX(DYNhelp,1)*DYNX(X_,2);
 /* Linear system of equations to solve. */
DYNX(F_,6) = RememberSimple_(DYNX(F_,6), 0);
SolveScalarLinearParametric(DYNX(DP_,11),"m", DYNX(W_,15),"F_xWhl", DYNX(F_,6),
  "der(v_x)");
 /* End of Equation Block */ 

DYNX(W_,13) = DYNX(DP_,5)*DYNX(W_,10);
 /* Linear system of equations to solve. */
DYNX(F_,3) = RememberSimple_(DYNX(F_,3), 1);
SolveScalarLinearParametric(DYNX(DP_,6),"J_y",  -((DYNX(X_,4)+DYNX(W_,13))*(
  DYNX(DP_,12)+DYNX(DP_,13))+DYNX(DP_,11)*DYNX(F_,6)*DYNX(DP_,14)+9.80665*
  DYNX(DP_,11)*DYNX(DP_,12))," -((F_sr+F_dr)*(lf+lr)+m*der(v_x)*h+9.80665*(m*lf))",
   DYNX(F_,3),"der(w_b)");
 /* End of Equation Block */ 

DYNX(W_,1) = IF LessTime(1, 0) THEN 0 ELSE 1;
DYNX(W_,2) = 9.80665*DYNX(W_,1)*DYNX(DP_,11);
if (NewParameters_) {
DYNX(DYNhelp,2) = divinvGuarded(DYNX(DP_,2),"Ratio");
}
DYNX(W_,3) = DYNX(DYNhelp,2)*DYNX(W_,2)*DYNX(DP_,7);
DYNX(W_,6) = IF Less(DYNX(X_,1),"w_Pm", 100.0,"100.0", 0) THEN RealBmin(
  DYNX(W_,3), 200) ELSE RealBmin(DYNX(W_,3), divGuarded(20000.0,"20000.0",
  DYNX(X_,1),"w_Pm"));
if (NewParameters_) {
DYNX(DYNhelp,3) = divinvGuarded(DYNX(DP_,1),"TimeConstant");
}
DYNX(F_,0) = DYNX(DYNhelp,3)*(DYNX(W_,6)-DYNX(X_,0));
 /* Linear system of equations to solve. */
DYNX(W_,7) = RememberSimple_(DYNX(W_,7), 2);
SolveScalarLinearParametric( -DYNX(DP_,2)," -Ratio",  -DYNX(X_,2)," -T_WhlRot", 
  DYNX(W_,7),"T_Pm");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
DYNX(F_,1) = RememberSimple_(DYNX(F_,1), 3);
SolveScalarLinearParametric(DYNX(DP_,0),"J_Pm", DYNX(X_,0)-DYNX(W_,7),
  "T_PmInternal-T_Pm", DYNX(F_,1),"der(w_Pm)");
 /* End of Equation Block */ 

DYNX(W_,9) = DYNX(DYNhelp,2)*DYNX(X_,1);

 /* Linear system of equations to solve. */
/* Tag: simulation.linear[1] */
DYNX(W_,18) = RememberSimple_(DYNX(W_,18), 4);
SolveScalarLinearParametric(DYNX(DP_,13)+DYNX(DP_,12),"lr+lf", DYNX(W_,15)*
  DYNX(DP_,14)+DYNX(DP_,6)*DYNX(F_,3)+9.80665*DYNX(DP_,12)*DYNX(DP_,11),
  "F_xWhl*h+J_y*der(w_b)+9.80665*(lf*m)", DYNX(W_,18),"F_rz");
DYNX(W_,16) = 9.80665*DYNX(DP_,11)-DYNX(W_,18);
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
DYNX(W_,17) = RememberSimple_(DYNX(W_,17), 5);
SolveScalarLinear( -DYNX(DP_,9)*DYNX(W_,16)," -CC_x*F_zWhl",  -DYNX(W_,15),
  " -F_xWhl", DYNX(W_,17),"s_x");
 /* End of Equation Block */ 

{ /* Non-linear system of equations to solve. */
/* Tag: simulation.nonlinear[1] */
/* Introducing 3 common subexpressions used in 3 expressions */
/* Of the common subexpressions 3 are reals, 0 are integers, and 0
   are booleans. */
const char*const varnames_[]={"w_WhlRot"};
const double nominal_[]={1.0};
NonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 1, 0, 0, 1, 6, 2, 
  DYNX(DYNhelp,4), 39, DYNX(did_->helpvari_vec,0), 23);
NonLinearSystemSave(DYNX(W_,17), 0);
NonLinearSystemSave(DYNX(X_,6), 1);
SetInitVectorNH(x__, 1, DYNX(W_,8), Remember_(DYNX(W_,8), 6));
Residues;
DYNX(DYNhelp,43) = DYNX(DP_,7)*DYNX(W_,8);
DYNX(DYNhelp,44) = fabs(DYNX(DYNhelp,43));
DYNX(DYNhelp,45) = RealBmax(DYNX(DYNhelp,44), DYNX(DP_,15));
SetVector(residue__, 1, DYNX(DYNhelp,43)-DYNX(X_,6)-DYNX(W_,17)*DYNX(DYNhelp,45));

Jacobian(Jacobian__)
MatrixZeros(Jacobian__);
SetMatrixLeading(Jacobian__, 1, 1, 1, DYNX(DP_,7)-DYNX(W_,17)*(IF fabs(
  DYNX(DYNhelp,43)) > DYNX(DP_,15) THEN DYNX(DP_,7)*(IF DYNX(DYNhelp,43) > 0
   THEN 1 ELSE -1) ELSE 0.0));

SolveNonLinearSystemOfEquationsNH(Jacobian__, 0, 0, 0, residue__, x__, 1, 
  "Tag: simulation.nonlinear[1]");
DYNX(W_,8) = GetVector(x__, 1);
EndNonLinearSystemOfEquationsNH(residue__, x__, 1);
 /* End of Non-Linear Equation Block */ }



DYNX(F_,2) = DYNX(DP_,3)*(DYNX(W_,9)-DYNX(W_,8));
DYNX(W_,11) =  -DYNX(X_,3)*DYNX(DP_,12);
DYNX(F_,5) = DYNX(DP_,4)*DYNX(W_,11);

AcceptedSection1

AcceptedSection2
DYNX(W_,12) =  -DYNX(F_,3)*DYNX(DP_,12);
DYNX(W_,14) = DYNX(DP_,5)*DYNX(W_,11);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("g", "[m/s2]", 0, 9.80665, 0.0,0.0,0.0,0,513)
DeclareVariable("APed", "[1]", 1, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("F_xReq", "[N]", 2, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("T_PmReq1", "[N.m]", 3, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("T_PmMax", "[N.m]", 4, 200, 0.0,0.0,0.0,0,513)
DeclareVariable("P_PmMax", "[W]", 5, 20000.0, 0.0,0.0,0.0,0,513)
DeclareParameter("J_Pm", "[kg.m2]", 0, 0.25, 0.0,0.0,0.0,0,560)
DeclareParameter("TimeConstant", "[s]", 1, 0.05, 0.0,0.0,0.0,0,560)
DeclareVariable("T_PmReq2", "[N.m]", 6, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("T_PmInternal", "[N.m]", 0, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(T_PmInternal)", "[W]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("T_Pm", "[N.m]", 7, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("w_Pm", "[rad/s]", 1, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(w_Pm)", "[rad/s2]", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("Ratio", "[1]", 2, 10, 0.0,0.0,0.0,0,560)
DeclareState("T_WhlRot", "[N.m]", 2, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(T_WhlRot)", "[W]", 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("w_WhlRot", "[rad/s]", 8, 0.0, 0.0,0.0,0.0,0,576)
DeclareParameter("C_Drv", "[N.m/rad]", 3, 23000, 0.0,0.0,0.0,0,560)
DeclareVariable("w_Drv", "[rad/s]", 9, 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("C_z", "[N/m]", 4, 30000.0, 0.0,0.0,0.0,0,560)
DeclareParameter("D_z", "[N.s/m]", 5, 2500.0, 0.0,0.0,0.0,0,560)
DeclareParameter("J_y", "[kg.m2]", 6, 3000, 0.0,0.0,0.0,0,560)
DeclareState("w_b", "[rad/s]", 3, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(w_b)", "[rad/s2]", 3, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("v_zr", "[m/s]", 10, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("v_zf", "[m/s]", 11, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("der(v_zf)", "[m/s2]", 12, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("F_sr", "[N]", 4, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(F_sr)", "[N/s]", 4, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("F_dr", "[N]", 13, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("F_sf", "[N]", 5, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(F_sf)", "[N/s]", 5, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("F_df", "[N]", 14, 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("Radius", "[m]", 7, 0.3, 0.0,0.0,0.0,0,560)
DeclareParameter("J_Whl", "[kg.m2]", 8, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("CC_x", "[1]", 9, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("mu_Peak", "[1]", 10, 0.6, 0.0,0.0,0.0,0,560)
DeclareVariable("F_xWhl", "[N]", 15, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("F_zWhl", "[N]", 16, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("v_xWhl", "[m/s]", "v_x", 1, 1, 6, 0)
DeclareVariable("s_x", "[1]", 17, 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("m", "[kg]", 11, 1500, 0.0,1E+100,0.0,0,560)
DeclareParameter("lf", "[m]", 12, 1.25, 0.0,0.0,0.0,0,560)
DeclareParameter("lr", "[m]", 13, 1.5, 0.0,0.0,0.0,0,560)
DeclareParameter("h", "[m]", 14, 0.4, 0.0,0.0,0.0,0,560)
DeclareState("v_x", "[m/s]", 6, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(v_x)", "[m/s2]", 6, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("F_rz", "[N]", 18, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("ModelTyreSlip", "[:#(type=Boolean)]", 19, true, 0.0,0.0,0.0,0,515)
DeclareVariable("ModelWheelInertia", "[:#(type=Boolean)]", 20, false, 0.0,0.0,\
0.0,0,515)
DeclareVariable("ModelTyreFrictionSaturation", "[:#(type=Boolean)]", 21, false, \
0.0,0.0,0.0,0,515)
DeclareParameter("v_Eps", "[m/s]", 15, 0.001, 0.0,0.0,0.0,0,560)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,18), 0.0, 4);
DoRemember_(DYNX(W_,7), 0.0, 2);
DoRemember_(DYNX(F_,6), 0.0, 0);
DoRemember_(DYNX(F_,1), 0.0, 3);
DoRemember_(DYNX(F_,3), 0.0, 1);
DoRemember_(DYNX(W_,17), 0.0, 5);
DoRemember_(DYNX(W_,8), 0.0, 6);
EndEqBlock
EndDataBlock
